### ISSUE TITLE
dep support / semantic versioning

### ISSUE THREAD

**Issue by julienschmidt** [julienschmidt/httprouter#189]
HttpRouter should support https://github.com/golang/dep

**Comment by ChristianSiegert** [comment]
Having httprouter vendored with Go dep and trying to update it with `dep ensure -update github.com/julienschmidt/httprouter` updates to httprouter v1.1 from June 2015.

Can you please create a new release so Go dep will fetch the latest available stable code?

As a workaround I edited `Gopkg.toml` and changed the entry for httprouter to:

```toml
[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  revision = "348b672cd90d8190f8240323e372ecd1e66b59dc"
```

Afterwards I ran `dep ensure -update github.com/julienschmidt/httprouter`.
